stages:
  format_data:
    cmd: python src/data/format_data.py data/raw/smoking_driking_dataset_Ver01.csv data/interim/format_data.csv
    deps:
      - data/raw/smoking_driking_dataset_Ver01.csv
      - src/data/format_data.py
    outs:
      - data/interim/format_data.csv

  remove_duplicates:
    cmd: python src/data/remove_duplicates.py data/interim/format_data.csv data/interim/remove_duplicates.csv
    deps:
      - data/interim/format_data.csv
      - src/data/remove_duplicates.py
    outs:
      - data/interim/remove_duplicates.csv

  handle_outliers:
    cmd: python src/data/handle_outliers.py data/interim/remove_duplicates.csv data/interim/handle_outliers.csv
    deps:
      - data/interim/remove_duplicates.csv
      - src/data/handle_outliers.py
    outs:
      - data/interim/handle_outliers.csv

  one_hot_encode_data:
    cmd: python src/data/encode_data.py data/interim/handle_outliers.csv data/processed/processed_data.csv
    deps:
      - data/interim/handle_outliers.csv
      - src/data/encode_data.py
    outs:
      - data/processed/processed_data.csv

  prepare_datasets:
    cmd: python src/models/prepare_datasets.py data/processed/processed_data.csv data/processed/train.csv data/processed/val.csv
    deps:
      - data/processed/processed_data.csv
      - src/models/prepare_datasets.py
    outs:
      - data/processed/train.csv
      - data/processed/val.csv

  train_model:
    cmd: python src/models/train_model.py data/processed/train.csv data/processed/val.csv reports/metrics.json models/model.clf
    deps:
      - data/processed/val.csv
      - data/processed/train.csv
      - src/models/train_model.py
    outs:
      - models/model.clf
      - reports/metrics.json

